# Generated by Django 2.2.15 on 2020-08-05 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ia_staff',
        ),
    ]
