# Generated by Django 2.2.15 on 2020-08-05 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_userprofile_ia_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='ia_staff',
            new_name='is_staff',
        ),
    ]
